### ISSUE TITLE
OptionHandler output string format issue

### ISSUE THREAD

**Issue by taemin00** [mj610-kim/excellent-code#45]
현재 옵션 핸들러에서 "-p" 혹은 "" 옵션에 따라 처리 후, output String에 \n을 붙여서 리턴하고 있습니다.
하지만 CH의 output String 처리 부분을 보니, println이나 setNextLine 함수로 인해 write시 \n이 2번 들어갈 것으로 보입니다.

String output = handleInput(input);
System.out.println("output: " + output);
localFileWriter.setNextLine(output);

따라서 OptionHandler에서 출력되는 문장에는 \n을 뺄까 하는데, 의견 주시면 감사하겠습니다

**Comment by mj610-kim** [comment]
@taemin00 님, 말씀하신 대로 OptionHandler.toString()에서의 최종 `\n`만 빼면 버그가 해결 될 것으로 보입니다. 동의하신다면, bug fix 요청드려도 될까요?
