### ISSUE TITLE
`input.txt`를 git에 포함할지 여부 판단

### ISSUE THREAD

**Issue by mj610-kim** [mj610-kim/excellent-code#55]
https://github.com/mj610-kim/excellent-code/blob/28d6ab9919f4032740a1f5a67def1de5f929e1dc/EmployeeManagementSystem/input.txt

input.txt는 여러 테스트를 진행하면서 달라질 수 도 있고, 사실 `EmployeementManagementSystem` 의 일부라고 볼 수 없다는 의견도 있을 수 있을 것 같습니다. `.gitignore` 에 `input.txt`, `output.txt`를 포함해 각 환경에서 개발자가 자유롭게 입출력 샘플을 사용할 수 있게 하면 좋을 것 같습니다.

**Comment by mj610-kim** [comment]
@kwonhj0116 님 @taemin00 님 @seongjin-Park210님 의견 주시면 감사하겠습니다!

**Comment by taemin00** [comment]
넵 저도 input/output.txt는 github에서 제외하는 것이 좋을 것 같습니다!
